### ISSUE TITLE
Modifying the results output page

### ISSUE THREAD

**Issue by codingprojects** [vlevit/q10r#1]
Is it possible to change the code for the results page so that you get a column per question asked and rows with all answers to that, followed by a percentage (=number of people that answered with that multiple choice question divided by number of people that filled in the questionnaire X 100 ).

So for example: say 10 people filled in the texteditor questionnaire and 7 of those answered emacs, you may get something like this:

What text editor do you use ?
Emacs  70%
Vi          10%
Ed         10%
Other    10%

I am also thinking of not needing users to type in their name, but do require them to have a unique IP per person entering. This way, while the questionnaire can then be anonymous, a same person can't cheat the program by answering the questionnaire several times.

Can you also allow users to type in their country of residence ?

Is it btw possible to automatically detect their country from the IP and block the response if it doesn't match the typed in country, and also allow questionnaires to be answered if the person filling it in is part of a certain country ?
This would then allow questionnaires to be made country-specific and allow counting only those people that are from that country (also important for calculating %).

**Comment by vlevit** [comment]
It should be possible but it's out of scope of this tiny personal project.

Check `templates/results.html` for results output page.
